In [13]:
import numpy as np

In [14]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
2 * x

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
2 * a + b

array([12, 24, 36])

In [17]:
c = np.array([[0, 2, 4], [6, 8, 10]])
print(c.ndim)
print(c.shape)

2
(2, 3)


In [18]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [19]:
a[a % 2 == 0]

array([0, 2, 4, 6])

In [20]:
x = np.array([1, 2.0, 3])
x.dtype

dtype('float64')

In [21]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [22]:
np.arange(3, 21, 2)  # 시작, 끝(포함하지 않음), 단계

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [23]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [25]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [26]:
b = a.reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
np.hstack([b, b]) #vstack

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [48]:
x = np.arange(1, 1000001)
y = np.arange(1000001, 2000001)
z = np.zeros_like(x)

In [49]:
%%time
for i in range(1000000):
    z[i] = x[i] + y[i]

CPU times: user 673 ms, sys: 4.6 ms, total: 678 ms
Wall time: 676 ms


In [50]:
%%time
z = x + y

CPU times: user 4.02 ms, sys: 2.84 ms, total: 6.86 ms
Wall time: 3.94 ms


In [ ]:
np.log(a + 1)

In [ ]:
a.argmin()  # 최솟값의 위치

In [ ]:
a.sum()

In [ ]:
a.mean()

In [51]:
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [52]:
np.sort(a)  # axis=-1 또는 axis=1 과 동일


array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [53]:
np.sort(a, axis=0)


array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])